directories:
  output: dist-electron
  buildResources: build
appId: com.companion.app
productName: Companion App
files:
  - filter:
      - dist/**/*
      - public/electron.js
      - node_modules/**/*
win:
  target: nsis
  icon: public/202.ico
mac:
  target: dmg
  icon: public/favicon.ico
linux:
  target: AppImage
  icon: public/favicon.ico
electronVersion: 37.2.0
